adding app files: attempt 1
Lowgular/project-simple-app-taskilicious-ng-material pull request #10
Opened 2023-02-18 21:46 UTC by uurunov

@matledzewicz

2023-02-18 21:54 UTC, uurunov commented
Hi. I have finished all tasks except '(Extra) Category Sort Dropdown', '(Extra) Edit Task Form: Add Image support', and '(Extra) Create Task Form: Add task image'.

2023-02-19 11:38 UTC, gradzio requested changes

2023-02-19 11:38 UTC, gradzio commented on src/app/components/add-edit-category/add_edit_category.component.ts
> +            if (params.hasOwnProperty('id') && params['id'] > 0) {
imperative programming

2023-02-19 11:38 UTC, gradzio commented on src/app/components/add-edit-category/add_edit_category.component.ts
> +    name: string = '';
mutable component properties

2023-02-19 11:38 UTC, gradzio commented on src/app/models/task.model.ts
> +    imageUrl: string | any,
optional model properties

2023-02-19 11:38 UTC, closed without merging

2023-02-19 14:07 UTC, uurunov commented
@gradzio I have read your comments but I am not clear about the next thing I should do now to meet task requirement. I mean, I do not understand what is wrong with the code where you left comments, sir. Please, help and guide me.

2023-02-19 14:45 UTC, uurunov reviewed
@gradzio I have read your comments but I am not clear about the next thing I should do now to meet task requirement. I mean, I do not understand what is wrong with the code where you left comments, sir. Please, help and guide me.

2023-02-19 15:11 UTC, uurunov commented
@gradzio I have read your comments but I am not clear about the next thing
I should do now to meet task requirement. I mean, I do not understand what
is wrong with the code where you left comments, sir. Please, help and guide
me.

On Sun, 19 Feb 2023 at 16:39 gradzio ***@***.***> wrote:

> Closed #10
> <https://github.com/Lowgular/project-simple-app-taskilicious-ng-material/pull/10>
> .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Lowgular/project-simple-app-taskilicious-ng-material/pull/10#event-8555083297>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQNDCK4FBLRQ7XGGWDWDNWDWYIA5NANCNFSM6AAAAAAVASHPVY>
> .
> You are receiving this because you authored the thread.Message ID:
> <Lowgular/project-simple-app-taskilicious-ng-material/pull/10/issue_event/8555083297
> @github.com>
>